# Generated by Django 3.1.7 on 2021-03-22 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0004_auto_20210322_0905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
