# Generated by Django 3.1.7 on 2021-03-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0008_auto_20210322_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='active_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
