# Generated by Django 3.1.7 on 2021-03-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0009_comment_active_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
